version: '3.8'

services:
  redis-server:
    container_name: redis
    image: redis:6.2.2

  node-app:
    build: .
    container_name: node-app
    command: npm run start
    volumes:
      - .:/usr/app/
    ports:
      - "3000:3000"
    depends_on:
      - redis-server
    environment:
      NODE_ENV: development
      REDIS_HOST: redis-server
      REDIS_PORT: 6379
